apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::230653850892:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::230653850892:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:master
kind: ConfigMap
metadata:
  # annotations:
  #   kubectl.kubernetes.io/last-applied-configuration: |
  #     {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::230653850892:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-01-31T06:26:52Z"
  # managedFields:
  # - apiVersion: v1
  #   fieldsType: FieldsV1
  #   fieldsV1:
  #     f:data:
  #       .: {}
  #       f:mapRoles: {}
  #     f:metadata:
  #       f:annotations:
  #         .: {}
  #         f:kubectl.kubernetes.io/last-applied-configuration: {}
  #   manager: kubectl-client-side-apply
    # operation: Update
    # time: "2021-01-31T06:26:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "171471"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 30da1c9c-2330-41a0-a8b7-1efee874e786
